-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2017-04-23 18:23:52 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




DROP TABLE Bilet CASCADE CONSTRAINTS ;

DROP TABLE Cennik CASCADE CONSTRAINTS ;

DROP TABLE Ceny CASCADE CONSTRAINTS ;

DROP TABLE Film CASCADE CONSTRAINTS ;

DROP TABLE Gatunek CASCADE CONSTRAINTS ;

DROP TABLE Miejsce CASCADE CONSTRAINTS ;

DROP TABLE Sala CASCADE CONSTRAINTS ;

DROP TABLE Seans CASCADE CONSTRAINTS ;

DROP TABLE Sektor CASCADE CONSTRAINTS ;

DROP TABLE Typ_biletu CASCADE CONSTRAINTS ;

DROP TABLE Zdjecia CASCADE CONSTRAINTS ;

CREATE TABLE Bilet
  (
    id            INTEGER NOT NULL ,
    miejsce_id    INTEGER NOT NULL ,
    seans_id      INTEGER NOT NULL ,
    typ_biletu_id INTEGER
  ) ;
ALTER TABLE Bilet ADD CONSTRAINT Bilet_PK PRIMARY KEY ( id ) ;


CREATE TABLE Cennik
  ( id INTEGER NOT NULL , ceny_id INTEGER NOT NULL
  ) ;
ALTER TABLE Cennik ADD CONSTRAINT Cennik_PK PRIMARY KEY ( id ) ;


CREATE TABLE Ceny
  (
    id   INTEGER NOT NULL ,
    cena NUMBER (6,2) ,
    od   DATE ,
    DO   DATE
  ) ;
ALTER TABLE Ceny ADD CONSTRAINT Ceny_PK PRIMARY KEY ( id ) ;


CREATE TABLE Film
  (
    id            INTEGER NOT NULL ,
    opis          VARCHAR2 (255 CHAR) ,
    tytul         VARCHAR2 (30 CHAR) ,
    rok_produkcji INTEGER ,
    dlugosc       INTEGER ,
    gatunek_id    INTEGER NOT NULL
  ) ;
ALTER TABLE Film ADD CONSTRAINT Film_PK PRIMARY KEY ( id ) ;


CREATE TABLE Gatunek
  (
    id    INTEGER NOT NULL ,
    nazwa VARCHAR2 (20 CHAR) ,
    opis  VARCHAR2 (255 CHAR)
  ) ;
ALTER TABLE Gatunek ADD CONSTRAINT Gatunek_PK PRIMARY KEY ( id ) ;


CREATE TABLE Miejsce
  ( id INTEGER NOT NULL , sektor_id INTEGER NOT NULL
  ) ;
ALTER TABLE Miejsce ADD CONSTRAINT Miejsce_PK PRIMARY KEY ( id ) ;


CREATE TABLE Sala
  (
    id      INTEGER NOT NULL ,
    nazwa   VARCHAR2 (30 CHAR) ,
    sala_id INTEGER
  ) ;
ALTER TABLE Sala ADD CONSTRAINT Sala_PK PRIMARY KEY ( id ) ;


CREATE TABLE Seans
  (
    id      INTEGER NOT NULL ,
    data    TIMESTAMP ,
    sala_id INTEGER NOT NULL ,
    film_id INTEGER NOT NULL
  ) ;
ALTER TABLE Seans ADD CONSTRAINT Seans_PK PRIMARY KEY ( id ) ;


CREATE TABLE Sektor
  ( id INTEGER NOT NULL , cennik_id INTEGER NOT NULL
  ) ;
ALTER TABLE Sektor ADD CONSTRAINT Sektor_PK PRIMARY KEY ( id ) ;


CREATE TABLE Typ_biletu
  (
    id        INTEGER NOT NULL ,
    nazwa     VARCHAR2 (10 CHAR) ,
    cennik_id INTEGER NOT NULL
  ) ;
ALTER TABLE Typ_biletu ADD CONSTRAINT Typ_biletu_PK PRIMARY KEY ( id ) ;


CREATE TABLE Zdjecia
  (
    id INTEGER NOT NULL ,
    zdjecie BLOB ,
    film_id INTEGER NOT NULL
  ) ;
ALTER TABLE Zdjecia ADD CONSTRAINT Zdjecia_PK PRIMARY KEY ( id ) ;


ALTER TABLE Bilet ADD CONSTRAINT Bilet_Miejsce_FK FOREIGN KEY ( miejsce_id ) REFERENCES Miejsce ( id ) ;

ALTER TABLE Bilet ADD CONSTRAINT Bilet_Seans_FK FOREIGN KEY ( seans_id ) REFERENCES Seans ( id ) ;

ALTER TABLE Bilet ADD CONSTRAINT Bilet_Typ_biletu_FK FOREIGN KEY ( seans_id ) REFERENCES Typ_biletu ( id ) ;

ALTER TABLE Cennik ADD CONSTRAINT Cennik_Ceny_FK FOREIGN KEY ( ceny_id ) REFERENCES Ceny ( id ) ;

ALTER TABLE Film ADD CONSTRAINT Film_Gatunek_FK FOREIGN KEY ( gatunek_id ) REFERENCES Gatunek ( id ) ;

ALTER TABLE Miejsce ADD CONSTRAINT Miejsce_Sektor_FK FOREIGN KEY ( sektor_id ) REFERENCES Sektor ( id ) ;

ALTER TABLE Seans ADD CONSTRAINT Seans_Film_FK FOREIGN KEY ( film_id ) REFERENCES Film ( id ) ;

ALTER TABLE Seans ADD CONSTRAINT Seans_Sala_FK FOREIGN KEY ( sala_id ) REFERENCES Sala ( id ) ;

ALTER TABLE Sektor ADD CONSTRAINT Sektor_Cennik_FK FOREIGN KEY ( cennik_id ) REFERENCES Cennik ( id ) ;

ALTER TABLE Typ_biletu ADD CONSTRAINT Typ_biletu_Cennik_FK FOREIGN KEY ( cennik_id ) REFERENCES Cennik ( id ) ;

ALTER TABLE Zdjecia ADD CONSTRAINT Zdjecia_Film_FK FOREIGN KEY ( film_id ) REFERENCES Film ( id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
