INSERT INTO SALA(NAZWA, SALA_ID) VALUES('SALA NIEBIESKA', 1);
INSERT INTO SALA(NAZWA, SALA_ID) VALUES('SALA ¯Ó£TA', 2);
INSERT INTO SALA(NAZWA, SALA_ID) VALUES('SALA ZIELONA', 3);
INSERT INTO SALA(NAZWA, SALA_ID) VALUES('SALA CZERWONA', 4);
INSERT INTO SALA(NAZWA, SALA_ID) VALUES('SALA CZARNA', 5);